export const REQCART_ADD_ITEM = "REQCART_ADD_ITEM";
export const REQCART_REMOVE_ITEM = "REQCART_REMOVE_ITEM";
export const REQCART_CLEAR_ITEMS = "REQCART_CLEAR_ITEMS";
export const REQCART_SAVE_SHIPPING_ADDRESS = "REQCART_SAVE_SHIPPING_ADDRESS";
export const REQCART_SAVE_PAYMENT_METHOD = "REQCART_SAVE_PAYMENT_METHOD";
