export const REQUEST_CREATE_REQUEST = "REQUEST_CREATE_REQUEST";
export const REQUEST_CREATE_SUCCESS = "REQUEST_CREATE_SUCCESS";
export const REQUEST_CREATE_FAIL = "REQUEST_CREATE_FAIL";
export const REQUEST_CREATE_RESET = "REQUEST_CREATE_RESET";

export const REQUEST_DETAILS_REQUEST = "REQUEST_DETAILS_REQUEST";
export const REQUEST_DETAILS_SUCCESS = "REQUEST_DETAILS_SUCCESS";
export const REQUEST_DETAILS_FAIL = "REQUEST_DETAILS_FAIL";

export const REQUEST_PAY_REQUEST = "REQUEST_PAY_REQUEST";
export const REQUEST_PAY_SUCCESS = "REQUEST_PAY_SUCCESS";
export const REQUEST_PAY_FAIL = "REQUEST_PAY_FAIL";
export const REQUEST_PAY_RESET = "REQUEST_PAY_RESET";

export const REQUEST_LIST_MY_REQUEST = "REQUEST_LIST_MY_REQUEST";
export const REQUEST_LIST_MY_SUCCESS = "REQUEST_LIST_MY_SUCCESS";
export const REQUEST_LIST_MY_FAIL = "REQUEST_LIST_MY_FAIL";
export const REQUEST_LIST_MY_RESET = "REQUEST_LIST_MY_RESET";
