export const SERVICE_LIST_REQUEST = "SERVICE_LIST_REQUEST";
export const SERVICE_LIST_SUCCESS = "SERVICE_LIST_SUCCESS";
export const SERVICE_LIST_FAIL = "SERVICE_LIST_FAIL";

export const SERVICE_DETAILS_REQUEST = "SERVICE_DETAILS_REQUEST";
export const SERVICE_DETAILS_SUCCESS = "SERVICE_DETAILS_SUCCESS";
export const SERVICE_DETAILS_FAIL = "SERVICE_DETAILS_FAIL";

export const SERVICE_CREATE_REVIEW_REQUEST = "SERVICE_CREATE_REVIEW_REQUEST";
export const SERVICE_CREATE_REVIEW_SUCCESS = "SERVICE_CREATE_REVIEW_SUCCESS";
export const SERVICE_CREATE_REVIEW_FAIL = "SERVICE_CREATE_REVIEW_FAIL";
export const SERVICE_CREATE_REVIEW_RESET = "SERVICE_CREATE_REVIEW_RESET";
