export const REQUEST_LIST_REQUEST = "REQUEST_LIST_REQUEST";
export const REQUEST_LIST_SUCCESS = "REQUEST_LIST_SUCCESS";
export const REQUEST_LIST_FAIL = "REQUEST_LIST_FAIL";

export const REQUEST_DETAILS_REQUEST = "REQUEST_DETAILS_REQUEST";
export const REQUEST_DETAILS_SUCCESS = "REQUEST_DETAILS_SUCCESS";
export const REQUEST_DETAILS_FAIL = "REQUEST_DETAILS_FAIL";

export const REQUEST_DELIVERED_REQUEST = "REQUEST_DELIVERED_REQUEST";
export const REQUEST_DELIVERED_SUCCESS = "REQUEST_DELIVERED_SUCCESS";
export const REQUEST_DELIVERED_FAIL = "REQUEST_DELIVERED_FAIL";
export const REQUEST_DELIVERED_RESET = "REQUEST_DELIVERED_RESET";

export const REQUEST_PAY_REQUEST = "ORDER_PAY_REQUEST";
export const REQUEST_PAY_SUCCESS = "ORDER_PAY_SUCCESS";
export const REQUEST_PAY_FAIL = "ORDER_PAY_FAIL";
export const REQUEST_PAY_RESET = "ORDER_PAY_RESET";
